// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taco.Challenge.Restaurant.Services.DataContext;

namespace Taco.Challenge.Restaurant.Services.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Taco.Challenge.Restaurant.Services.DataContext.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Wholesome Vegetarian Meals",
                            RestaurantId = 2380
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mains",
                            RestaurantId = 1361
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mains",
                            RestaurantId = 2438
                        },
                        new
                        {
                            Id = 4,
                            Name = "Vegetarian Curries",
                            RestaurantId = 1343
                        },
                        new
                        {
                            Id = 5,
                            Name = "Grills",
                            RestaurantId = 1029
                        },
                        new
                        {
                            Id = 6,
                            Name = "Tacos",
                            RestaurantId = 1029
                        },
                        new
                        {
                            Id = 7,
                            Name = "Vegetarian Menu",
                            RestaurantId = 1558
                        },
                        new
                        {
                            Id = 8,
                            Name = "Vegetarian Menu",
                            RestaurantId = 1641
                        },
                        new
                        {
                            Id = 9,
                            Name = "Appetizers",
                            RestaurantId = 830
                        },
                        new
                        {
                            Id = 10,
                            Name = "Salads",
                            RestaurantId = 830
                        },
                        new
                        {
                            Id = 11,
                            Name = "Sandwiches & Tacos",
                            RestaurantId = 830
                        },
                        new
                        {
                            Id = 12,
                            Name = "Seafood",
                            RestaurantId = 830
                        },
                        new
                        {
                            Id = 13,
                            Name = "Appetizers",
                            RestaurantId = 1076
                        },
                        new
                        {
                            Id = 14,
                            Name = "Salads",
                            RestaurantId = 1076
                        },
                        new
                        {
                            Id = 15,
                            Name = "Sandwiches & Tacos",
                            RestaurantId = 1076
                        },
                        new
                        {
                            Id = 16,
                            Name = "Seafood",
                            RestaurantId = 1076
                        },
                        new
                        {
                            Id = 17,
                            Name = "Grills",
                            RestaurantId = 935
                        },
                        new
                        {
                            Id = 18,
                            Name = "Grills",
                            RestaurantId = 989
                        },
                        new
                        {
                            Id = 19,
                            Name = "Grills",
                            RestaurantId = 1028
                        },
                        new
                        {
                            Id = 20,
                            Name = "Grills",
                            RestaurantId = 1031
                        },
                        new
                        {
                            Id = 21,
                            Name = "Grills",
                            RestaurantId = 1200
                        },
                        new
                        {
                            Id = 22,
                            Name = "Vegetarian Dishes",
                            RestaurantId = 1874
                        },
                        new
                        {
                            Id = 23,
                            Name = "Snacks & Starters",
                            RestaurantId = 895
                        },
                        new
                        {
                            Id = 24,
                            Name = "Vegetarian Currys",
                            RestaurantId = 859
                        },
                        new
                        {
                            Id = 25,
                            Name = "Vegetarian Dishes",
                            RestaurantId = 1491
                        },
                        new
                        {
                            Id = 26,
                            Name = "Vegetarian & Banting Meals",
                            RestaurantId = 1524
                        },
                        new
                        {
                            Id = 27,
                            Name = "Tacos (Served Day & Night)",
                            RestaurantId = 1269
                        },
                        new
                        {
                            Id = 28,
                            Name = "Vegan Light Meals",
                            RestaurantId = 1269
                        },
                        new
                        {
                            Id = 29,
                            Name = "Vegetarian Burger (Served Day & Night)",
                            RestaurantId = 1269
                        },
                        new
                        {
                            Id = 30,
                            Name = "Tacos (Served Day & Night)",
                            RestaurantId = 1270
                        },
                        new
                        {
                            Id = 31,
                            Name = "Vegan Light Meals",
                            RestaurantId = 1270
                        },
                        new
                        {
                            Id = 32,
                            Name = "Vegetarian Burger (Served Day & Night)",
                            RestaurantId = 1270
                        },
                        new
                        {
                            Id = 33,
                            Name = "Tacos (Served Day & Night)",
                            RestaurantId = 1381
                        },
                        new
                        {
                            Id = 34,
                            Name = "Vegan Light Meals",
                            RestaurantId = 1381
                        },
                        new
                        {
                            Id = 35,
                            Name = "Vegetarian Burger (Served Day & Night)",
                            RestaurantId = 1381
                        },
                        new
                        {
                            Id = 36,
                            Name = "Vegan Light Meals",
                            RestaurantId = 1484
                        },
                        new
                        {
                            Id = 37,
                            Name = "Vegetarian Burger (Served Day & Night)",
                            RestaurantId = 1484
                        },
                        new
                        {
                            Id = 38,
                            Name = "Tacos (Served Day & Night)",
                            RestaurantId = 1487
                        },
                        new
                        {
                            Id = 39,
                            Name = "Vegan Light Meals",
                            RestaurantId = 1487
                        },
                        new
                        {
                            Id = 40,
                            Name = "Vegetarian Burger (Served Day & Night)",
                            RestaurantId = 1487
                        },
                        new
                        {
                            Id = 41,
                            Name = "Tacos (Served Day & Night)",
                            RestaurantId = 1488
                        },
                        new
                        {
                            Id = 42,
                            Name = "Vegan Light Meals",
                            RestaurantId = 1488
                        },
                        new
                        {
                            Id = 43,
                            Name = "Vegetarian Burger (Served Day & Night)",
                            RestaurantId = 1488
                        },
                        new
                        {
                            Id = 44,
                            Name = "Vegetarian Burgers (Served Day & Night)",
                            RestaurantId = 2425
                        });
                });

            modelBuilder.Entity("Taco.Challenge.Restaurant.Services.DataContext.Entities.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("MenuItem");

                    b.HasData(
                        new
                        {
                            Id = 941580,
                            CategoryId = 1,
                            Name = "Vegetarian Burger",
                            Price = 36.899999999999999
                        },
                        new
                        {
                            Id = 941581,
                            CategoryId = 1,
                            Name = "Vegetarian Stir Fry & Rice",
                            Price = 42.899999999999999
                        },
                        new
                        {
                            Id = 941582,
                            CategoryId = 1,
                            Name = "Vegetarian Schwarma",
                            Price = 41.899999999999999
                        },
                        new
                        {
                            Id = 1315807,
                            CategoryId = 2,
                            Name = "Crispy Tacos",
                            Price = 80.0
                        },
                        new
                        {
                            Id = 1315808,
                            CategoryId = 2,
                            Name = "Soft Tacos",
                            Price = 80.0
                        },
                        new
                        {
                            Id = 1137091,
                            CategoryId = 3,
                            Name = "Crispy Tacos",
                            Price = 70.0
                        },
                        new
                        {
                            Id = 1137092,
                            CategoryId = 3,
                            Name = "Soft Tacos",
                            Price = 70.0
                        },
                        new
                        {
                            Id = 1346579,
                            CategoryId = 4,
                            Name = "The OMG Dhal & Brinjals",
                            Price = 73.950000000000003
                        },
                        new
                        {
                            Id = 1346580,
                            CategoryId = 4,
                            Name = "The Powerhouse Dhal Makhni",
                            Price = 79.950000000000003
                        },
                        new
                        {
                            Id = 1346584,
                            CategoryId = 4,
                            Name = "''Howzit Chana",
                            Price = 73.950000000000003
                        },
                        new
                        {
                            Id = 1346585,
                            CategoryId = 4,
                            Name = "Bombay Potatoes",
                            Price = 74.950000000000003
                        },
                        new
                        {
                            Id = 1346586,
                            CategoryId = 4,
                            Name = "\"The \"can't get enough of\" Aloo Jeera\",",
                            Price = 69.950000000000003
                        },
                        new
                        {
                            Id = 1346587,
                            CategoryId = 4,
                            Name = "The Green Velvet Aloo Palak",
                            Price = 78.950000000000003
                        },
                        new
                        {
                            Id = 1346588,
                            CategoryId = 4,
                            Name = "Paneer & Aloo Palak",
                            Price = 91.950000000000003
                        },
                        new
                        {
                            Id = 1346589,
                            CategoryId = 4,
                            Name = "Paneer & Aloo Tikka Masala",
                            Price = 99.950000000000003
                        },
                        new
                        {
                            Id = 1346590,
                            CategoryId = 4,
                            Name = "Paneer & Aloo Makhni",
                            Price = 91.950000000000003
                        },
                        new
                        {
                            Id = 1346591,
                            CategoryId = 4,
                            Name = "The oh so comforting Paneer Korma",
                            Price = 99.950000000000003
                        },
                        new
                        {
                            Id = 1346592,
                            CategoryId = 4,
                            Name = "Paneer Palak",
                            Price = 99.950000000000003
                        },
                        new
                        {
                            Id = 1346593,
                            CategoryId = 4,
                            Name = "Gentle Paneer Makhni",
                            Price = 99.950000000000003
                        },
                        new
                        {
                            Id = 1346594,
                            CategoryId = 4,
                            Name = "Paneer Tikka Masala",
                            Price = 99.950000000000003
                        },
                        new
                        {
                            Id = 1346595,
                            CategoryId = 4,
                            Name = "Our Veg & Paneer Signature Meal",
                            Price = 99.950000000000003
                        },
                        new
                        {
                            Id = 1346596,
                            CategoryId = 4,
                            Name = "Chickpea, Veg & Coconut Exotica",
                            Price = 99.950000000000003
                        },
                        new
                        {
                            Id = 1346597,
                            CategoryId = 4,
                            Name = "It hurts so good Vegetable Jalfrezi",
                            Price = 99.950000000000003
                        },
                        new
                        {
                            Id = 1263596,
                            CategoryId = 5,
                            Name = "Grilled Hard Tacos",
                            Price = 86.0
                        },
                        new
                        {
                            Id = 1263588,
                            CategoryId = 6,
                            Name = "Carne Tacos",
                            Price = 92.0
                        },
                        new
                        {
                            Id = 1263589,
                            CategoryId = 6,
                            Name = "Pollo Tacos",
                            Price = 87.0
                        },
                        new
                        {
                            Id = 1263590,
                            CategoryId = 6,
                            Name = "Puerco Tacos",
                            Price = 92.0
                        },
                        new
                        {
                            Id = 1263591,
                            CategoryId = 6,
                            Name = "Pescado Tacos",
                            Price = 87.0
                        },
                        new
                        {
                            Id = 1263592,
                            CategoryId = 6,
                            Name = "Vegetariano Tacos",
                            Price = 85.0
                        },
                        new
                        {
                            Id = 1392554,
                            CategoryId = 7,
                            Name = "Teriyaki Tofu Starter (Vegan)",
                            Price = 40.0
                        },
                        new
                        {
                            Id = 1392555,
                            CategoryId = 7,
                            Name = "LA Flight Bowl (Gluten-free)",
                            Price = 65.0
                        },
                        new
                        {
                            Id = 1392558,
                            CategoryId = 7,
                            Name = "Naughty Girl (Vegan)",
                            Price = 75.0
                        },
                        new
                        {
                            Id = 1392568,
                            CategoryId = 7,
                            Name = "Red Summer (Vegan/Gluten-free)",
                            Price = 75.0
                        },
                        new
                        {
                            Id = 1392598,
                            CategoryId = 8,
                            Name = "Teriyaki Tofu Starter (Vegan)",
                            Price = 40.0
                        },
                        new
                        {
                            Id = 1266160,
                            CategoryId = 9,
                            Name = "Wise Choice Fish Tacos",
                            Price = 96.5
                        },
                        new
                        {
                            Id = 1266161,
                            CategoryId = 9,
                            Name = "Wise Choice Shrimp Tacos",
                            Price = 120.0
                        },
                        new
                        {
                            Id = 1266199,
                            CategoryId = 10,
                            Name = "Taco Salad",
                            Price = 112.0
                        },
                        new
                        {
                            Id = 1266189,
                            CategoryId = 11,
                            Name = "Smothered Chicken Sandwich",
                            Price = 101.0
                        },
                        new
                        {
                            Id = 1266190,
                            CategoryId = 11,
                            Name = "Philly Cheese Steak Sandwich",
                            Price = 97.5
                        },
                        new
                        {
                            Id = 1266191,
                            CategoryId = 11,
                            Name = "Chicken Speed Way Sandwich",
                            Price = 106.5
                        },
                        new
                        {
                            Id = 1266192,
                            CategoryId = 11,
                            Name = "Buffalo Chicken Tacos",
                            Price = 90.0
                        },
                        new
                        {
                            Id = 1266193,
                            CategoryId = 11,
                            Name = "Baja Fish Tacos",
                            Price = 95.5
                        },
                        new
                        {
                            Id = 1266194,
                            CategoryId = 11,
                            Name = "Baja Shrimp Tacos",
                            Price = 123.5
                        },
                        new
                        {
                            Id = 1266202,
                            CategoryId = 12,
                            Name = "Baja Fish Tacos",
                            Price = 95.5
                        },
                        new
                        {
                            Id = 1266203,
                            CategoryId = 12,
                            Name = "Baja Shrimp Tacos",
                            Price = 123.5
                        },
                        new
                        {
                            Id = 1266282,
                            CategoryId = 13,
                            Name = "Wise Choice Fish Tacos",
                            Price = 96.5
                        },
                        new
                        {
                            Id = 1266283,
                            CategoryId = 13,
                            Name = "Wise Choice Shrimp Tacos",
                            Price = 120.0
                        },
                        new
                        {
                            Id = 1266321,
                            CategoryId = 14,
                            Name = "Taco Salad",
                            Price = 112.0
                        },
                        new
                        {
                            Id = 1266311,
                            CategoryId = 15,
                            Name = "Smothered Chicken Sandwich",
                            Price = 101.0
                        },
                        new
                        {
                            Id = 1266312,
                            CategoryId = 15,
                            Name = "Philly Cheese Steak Sandwich",
                            Price = 97.5
                        },
                        new
                        {
                            Id = 1266313,
                            CategoryId = 15,
                            Name = "Chicken Speed Way Sandwich",
                            Price = 106.5
                        },
                        new
                        {
                            Id = 1266314,
                            CategoryId = 15,
                            Name = "Buffalo Chicken Tacos",
                            Price = 90.0
                        },
                        new
                        {
                            Id = 1266315,
                            CategoryId = 15,
                            Name = "Baja Fish Tacos",
                            Price = 95.5
                        },
                        new
                        {
                            Id = 1266316,
                            CategoryId = 15,
                            Name = "Baja Shrimp Tacos",
                            Price = 123.5
                        },
                        new
                        {
                            Id = 1266324,
                            CategoryId = 16,
                            Name = "Baja Fish Tacos",
                            Price = 95.5
                        },
                        new
                        {
                            Id = 1266325,
                            CategoryId = 16,
                            Name = "Baja Shrimp Tacos",
                            Price = 123.5
                        },
                        new
                        {
                            Id = 1389883,
                            CategoryId = 17,
                            Name = "Falafel Taco",
                            Price = 106.0
                        },
                        new
                        {
                            Id = 1389884,
                            CategoryId = 17,
                            Name = "Free Range Chicken Taco",
                            Price = 113.0
                        },
                        new
                        {
                            Id = 1288551,
                            CategoryId = 18,
                            Name = "Falafel Taco",
                            Price = 106.0
                        },
                        new
                        {
                            Id = 1288632,
                            CategoryId = 18,
                            Name = "Free Range Chicken Taco",
                            Price = 113.0
                        },
                        new
                        {
                            Id = 1389786,
                            CategoryId = 19,
                            Name = "Falafel Taco",
                            Price = 106.0
                        },
                        new
                        {
                            Id = 1389787,
                            CategoryId = 19,
                            Name = "Free Range Chicken Taco",
                            Price = 113.0
                        },
                        new
                        {
                            Id = 1390077,
                            CategoryId = 20,
                            Name = "Falafel Taco",
                            Price = 106.0
                        },
                        new
                        {
                            Id = 1390078,
                            CategoryId = 20,
                            Name = "Free Range Chicken Taco",
                            Price = 113.0
                        },
                        new
                        {
                            Id = 1389980,
                            CategoryId = 21,
                            Name = "Falafel Taco",
                            Price = 106.0
                        },
                        new
                        {
                            Id = 1389981,
                            CategoryId = 21,
                            Name = "Free Range Chicken Taco",
                            Price = 113.0
                        },
                        new
                        {
                            Id = 1200133,
                            CategoryId = 22,
                            Name = "Vegetarian Foo Yong",
                            Price = 87.0
                        },
                        new
                        {
                            Id = 1200134,
                            CategoryId = 22,
                            Name = "Vegetarian Oyster Sauce",
                            Price = 87.0
                        },
                        new
                        {
                            Id = 1200135,
                            CategoryId = 22,
                            Name = "Stir Fry Chinese Green Vegetables",
                            Price = 87.0
                        },
                        new
                        {
                            Id = 1362967,
                            CategoryId = 23,
                            Name = "Tacos",
                            Price = 95.0
                        },
                        new
                        {
                            Id = 207208,
                            CategoryId = 24,
                            Name = "304 Aloo Peas-Dry",
                            Price = 91.0
                        },
                        new
                        {
                            Id = 207209,
                            CategoryId = 24,
                            Name = "305 Aloo Jeera",
                            Price = 91.0
                        },
                        new
                        {
                            Id = 207215,
                            CategoryId = 24,
                            Name = "311 Methi Malai Mutter",
                            Price = 103.0
                        },
                        new
                        {
                            Id = 769348,
                            CategoryId = 24,
                            Name = "303 Palak Paneer",
                            Price = 103.0
                        },
                        new
                        {
                            Id = 1020532,
                            CategoryId = 24,
                            Name = "302 Paneer Makhani",
                            Price = 103.0
                        },
                        new
                        {
                            Id = 1020535,
                            CategoryId = 24,
                            Name = "307 Punjabi Dum Aloo",
                            Price = 97.0
                        },
                        new
                        {
                            Id = 1020537,
                            CategoryId = 24,
                            Name = "308 Vegetable Korma",
                            Price = 109.0
                        },
                        new
                        {
                            Id = 1020538,
                            CategoryId = 24,
                            Name = "309 Vegetable Hyderabadi",
                            Price = 97.0
                        },
                        new
                        {
                            Id = 1020543,
                            CategoryId = 24,
                            Name = "312 Veg Jalfrezi",
                            Price = 97.0
                        },
                        new
                        {
                            Id = 1020552,
                            CategoryId = 24,
                            Name = "316 Daal Tadka",
                            Price = 91.0
                        },
                        new
                        {
                            Id = 1020553,
                            CategoryId = 24,
                            Name = "317 Daal Palak Lasooni",
                            Price = 97.0
                        },
                        new
                        {
                            Id = 1020566,
                            CategoryId = 24,
                            Name = "314 Allo Gobhi Adraki",
                            Price = 103.0
                        },
                        new
                        {
                            Id = 1020615,
                            CategoryId = 24,
                            Name = "320 Vegetable Mohini ",
                            Price = 103.0
                        },
                        new
                        {
                            Id = 1020623,
                            CategoryId = 24,
                            Name = "321 Paneer Lababdar",
                            Price = 109.0
                        },
                        new
                        {
                            Id = 881403,
                            CategoryId = 25,
                            Name = "Vegetarian Pizza",
                            Price = 85.0
                        },
                        new
                        {
                            Id = 1238151,
                            CategoryId = 25,
                            Name = "Vegetable Soup",
                            Price = 50.0
                        },
                        new
                        {
                            Id = 1238152,
                            CategoryId = 25,
                            Name = "Vegetable Burger & Chips",
                            Price = 65.0
                        },
                        new
                        {
                            Id = 1238153,
                            CategoryId = 25,
                            Name = "Vegetarian Pasta",
                            Price = 95.0
                        },
                        new
                        {
                            Id = 1238154,
                            CategoryId = 25,
                            Name = "Vegetable Curry",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 1238155,
                            CategoryId = 25,
                            Name = "Vegetable Platter",
                            Price = 110.0
                        },
                        new
                        {
                            Id = 1184604,
                            CategoryId = 26,
                            Name = "Grilled Lamb Chops",
                            Price = 150.0
                        },
                        new
                        {
                            Id = 1184606,
                            CategoryId = 26,
                            Name = "Prawns & Veggies Stir Fry",
                            Price = 130.0
                        },
                        new
                        {
                            Id = 1184607,
                            CategoryId = 26,
                            Name = "Vegetable Soup",
                            Price = 50.0
                        },
                        new
                        {
                            Id = 1184608,
                            CategoryId = 26,
                            Name = "Vegetable Burger & Chips",
                            Price = 65.0
                        },
                        new
                        {
                            Id = 1184609,
                            CategoryId = 26,
                            Name = "Vegetarian Pizza",
                            Price = 85.0
                        },
                        new
                        {
                            Id = 1184610,
                            CategoryId = 26,
                            Name = "Vegetarian Pasta",
                            Price = 95.0
                        },
                        new
                        {
                            Id = 1184611,
                            CategoryId = 26,
                            Name = "Vegetable Curry",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 1184612,
                            CategoryId = 26,
                            Name = "Vegetable Platter",
                            Price = 110.0
                        },
                        new
                        {
                            Id = 1332565,
                            CategoryId = 27,
                            Name = "BBQ Pulled Pork Taco",
                            Price = 105.0
                        },
                        new
                        {
                            Id = 1332566,
                            CategoryId = 27,
                            Name = "Buttermilk Fried Chicken Taco",
                            Price = 105.0
                        },
                        new
                        {
                            Id = 1332567,
                            CategoryId = 27,
                            Name = "Falafel Taco",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 1332568,
                            CategoryId = 27,
                            Name = "Loaded Nachos",
                            Price = 105.0
                        },
                        new
                        {
                            Id = 1332580,
                            CategoryId = 28,
                            Name = "Vegan Falafel Taco",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 1332557,
                            CategoryId = 29,
                            Name = "Veggie Burger",
                            Price = 76.0
                        },
                        new
                        {
                            Id = 1332673,
                            CategoryId = 30,
                            Name = "BBQ Pulled Pork Taco",
                            Price = 105.0
                        },
                        new
                        {
                            Id = 1332674,
                            CategoryId = 30,
                            Name = "Buttermilk Fried Chicken Taco",
                            Price = 105.0
                        },
                        new
                        {
                            Id = 1332675,
                            CategoryId = 30,
                            Name = "Falafel Taco",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 1332676,
                            CategoryId = 30,
                            Name = "Loaded Nachos",
                            Price = 105.0
                        },
                        new
                        {
                            Id = 1332688,
                            CategoryId = 31,
                            Name = "Vegan Falafel Taco",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 1332665,
                            CategoryId = 32,
                            Name = "Veggie Burger",
                            Price = 76.0
                        },
                        new
                        {
                            Id = 1332781,
                            CategoryId = 33,
                            Name = "BBQ Pulled Pork Taco",
                            Price = 105.0
                        },
                        new
                        {
                            Id = 1332782,
                            CategoryId = 33,
                            Name = "Buttermilk Fried Chicken Taco",
                            Price = 105.0
                        },
                        new
                        {
                            Id = 1332783,
                            CategoryId = 33,
                            Name = "Falafel Taco",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 1332784,
                            CategoryId = 33,
                            Name = "Loaded Nachos",
                            Price = 105.0
                        },
                        new
                        {
                            Id = 1332796,
                            CategoryId = 34,
                            Name = "Vegan Falafel Taco",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 1332773,
                            CategoryId = 35,
                            Name = "Veggie Burger",
                            Price = 76.0
                        },
                        new
                        {
                            Id = 1332904,
                            CategoryId = 36,
                            Name = "Vegan Falafel Taco",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 1332881,
                            CategoryId = 37,
                            Name = "Veggie Burger",
                            Price = 76.0
                        },
                        new
                        {
                            Id = 1327803,
                            CategoryId = 38,
                            Name = "BBQ Pulled Pork Taco",
                            Price = 105.0
                        },
                        new
                        {
                            Id = 1327804,
                            CategoryId = 38,
                            Name = "Buttermilk Fried Chicken Taco",
                            Price = 105.0
                        },
                        new
                        {
                            Id = 1327805,
                            CategoryId = 38,
                            Name = "Falafel Taco",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 1327806,
                            CategoryId = 38,
                            Name = "Loaded Nachos",
                            Price = 105.0
                        },
                        new
                        {
                            Id = 1327821,
                            CategoryId = 39,
                            Name = "Vegan Falafel Taco",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 1327793,
                            CategoryId = 40,
                            Name = "Veggie Burger",
                            Price = 76.0
                        },
                        new
                        {
                            Id = 1332997,
                            CategoryId = 41,
                            Name = "BBQ Pulled Pork Taco",
                            Price = 105.0
                        },
                        new
                        {
                            Id = 1332998,
                            CategoryId = 41,
                            Name = "Buttermilk Fried Chicken Taco",
                            Price = 105.0
                        },
                        new
                        {
                            Id = 1332999,
                            CategoryId = 41,
                            Name = "Falafel Taco",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 1333000,
                            CategoryId = 41,
                            Name = "Loaded Nachos",
                            Price = 105.0
                        },
                        new
                        {
                            Id = 1333012,
                            CategoryId = 42,
                            Name = "Vegan Falafel Taco",
                            Price = 99.0
                        },
                        new
                        {
                            Id = 1332989,
                            CategoryId = 43,
                            Name = "Veggie Burger",
                            Price = 76.0
                        },
                        new
                        {
                            Id = 1384510,
                            CategoryId = 44,
                            Name = "Vegetarian Classic Veggie Burger",
                            Price = 76.0
                        });
                });

            modelBuilder.Entity("Taco.Challenge.Restaurant.Services.DataContext.Entities.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("Suburb")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 2380,
                            City = "Pretoria",
                            LogoPath = "https://restaurantbanners.orderin.co.za/barcelos_109_cropped/620.jpg",
                            Name = "Barcelos",
                            Rank = 0,
                            Suburb = "Pretoria"
                        },
                        new
                        {
                            Id = 1361,
                            City = "Johannesburg",
                            LogoPath = "https://restaurantbanners.orderin.co.za/chiapas-eat-mexican_736_cropped/620.jpg",
                            Name = "CHIAPAS eat mexican",
                            Rank = 1,
                            Suburb = "Rosebank"
                        },
                        new
                        {
                            Id = 2438,
                            City = "Pretoria",
                            LogoPath = "https://restaurantbanners.orderin.co.za/chiapas-eat-mexican_736_cropped/620.jpg",
                            Name = "CHIAPAS eat mexican",
                            Rank = 8,
                            Suburb = "Brooklyn"
                        },
                        new
                        {
                            Id = 1343,
                            City = "Johannesburg",
                            LogoPath = "https://restaurantbanners.orderin.co.za/curry-up_722_cropped/620.jpg",
                            Name = "Curry Up",
                            Rank = 3,
                            Suburb = "Randburg"
                        },
                        new
                        {
                            Id = 1029,
                            City = "Johannesburg",
                            LogoPath = "https://restaurantbanners.orderin.co.za/el-jalapeno_528_cropped/620.jpg",
                            Name = "El Jalapeno",
                            Rank = 9,
                            Suburb = "Linden"
                        },
                        new
                        {
                            Id = 1558,
                            City = "Cape Town",
                            LogoPath = "https://restaurantbanners.orderin.co.za/hokey-poke_839_cropped/620.jpg",
                            Name = "Hokey Poke",
                            Rank = 8,
                            Suburb = "CBD"
                        },
                        new
                        {
                            Id = 1641,
                            City = "Cape Town",
                            LogoPath = "https://restaurantbanners.orderin.co.za/hokey-poke_839_cropped/620.jpg",
                            Name = "Hokey Poke",
                            Rank = 1,
                            Suburb = "Sea Point"
                        },
                        new
                        {
                            Id = 830,
                            City = "Johannesburg",
                            LogoPath = "https://restaurantbanners.orderin.co.za/hooters_413_cropped/620.jpg",
                            Name = "Hooters",
                            Rank = 0,
                            Suburb = "Fourways"
                        },
                        new
                        {
                            Id = 1076,
                            City = "Pretoria",
                            LogoPath = "https://restaurantbanners.orderin.co.za/hooters_413_cropped/620.jpg",
                            Name = "Hooters",
                            Rank = 6,
                            Suburb = "Pretoria"
                        },
                        new
                        {
                            Id = 935,
                            City = "Cape Town",
                            LogoPath = "https://restaurantbanners.orderin.co.za/hudsons_470_cropped/620.jpg",
                            Name = "Hudsons",
                            Rank = 5,
                            Suburb = "Green Point"
                        },
                        new
                        {
                            Id = 989,
                            City = "Cape Town",
                            LogoPath = "https://restaurantbanners.orderin.co.za/hudsons_470_cropped/620.jpg",
                            Name = "Hudsons",
                            Rank = 9,
                            Suburb = "Gardens"
                        },
                        new
                        {
                            Id = 1028,
                            City = "Cape Town",
                            LogoPath = "https://restaurantbanners.orderin.co.za/hudsons_470_cropped/620.jpg",
                            Name = "Hudsons",
                            Rank = 8,
                            Suburb = "Claremont"
                        },
                        new
                        {
                            Id = 1031,
                            City = "Johannesburg",
                            LogoPath = "https://restaurantbanners.orderin.co.za/hudsons_470_cropped/620.jpg",
                            Name = "Hudsons",
                            Rank = 1,
                            Suburb = "Parkhurst"
                        },
                        new
                        {
                            Id = 1200,
                            City = "Pretoria",
                            LogoPath = "https://restaurantbanners.orderin.co.za/hudsons_470_cropped/620.jpg",
                            Name = "Hudsons",
                            Rank = 0,
                            Suburb = "Hazelwood"
                        },
                        new
                        {
                            Id = 1874,
                            City = "Cape Town",
                            LogoPath = "https://restaurantbanners.orderin.co.za/jade-tavern_962_cropped/620.jpg",
                            Name = "Jade Tavern",
                            Rank = 4,
                            Suburb = "Kenilworth"
                        },
                        new
                        {
                            Id = 895,
                            City = "Cape Town",
                            LogoPath = "https://restaurantbanners.orderin.co.za/jamaica-me-crazy_453_cropped/620.jpg",
                            Name = "Jamaica Me Crazy",
                            Rank = 5,
                            Suburb = "Woodstock"
                        },
                        new
                        {
                            Id = 859,
                            City = "Cape Town",
                            LogoPath = "https://restaurantbanners.orderin.co.za/jewel-of-india_437_cropped/620.jpg",
                            Name = "Jewel of India",
                            Rank = 9,
                            Suburb = "Foreshore"
                        },
                        new
                        {
                            Id = 1491,
                            City = "Durban",
                            LogoPath = "https://restaurantbanners.orderin.co.za/jimmy-s-killer-prawns_158_cropped/620.jpg",
                            Name = "Jimmy's Killer Prawns",
                            Rank = 1,
                            Suburb = "Umhlanga"
                        },
                        new
                        {
                            Id = 1524,
                            City = "Johannesburg",
                            LogoPath = "https://restaurantbanners.orderin.co.za/jimmy-s-killer-prawns_158_cropped/620.jpg",
                            Name = "Jimmy's Killer Prawns",
                            Rank = 4,
                            Suburb = "Fordsburg"
                        },
                        new
                        {
                            Id = 1269,
                            City = "Cape Town",
                            LogoPath = "https://restaurantbanners.orderin.co.za/knead_652_cropped/620.jpg",
                            Name = "Knead",
                            Rank = 9,
                            Suburb = "Gardens"
                        },
                        new
                        {
                            Id = 1270,
                            City = "Cape Town",
                            LogoPath = "https://restaurantbanners.orderin.co.za/knead_652_cropped/620.jpg",
                            Name = "Knead",
                            Rank = 0,
                            Suburb = "Sea Point"
                        },
                        new
                        {
                            Id = 1381,
                            City = "Cape Town",
                            LogoPath = "https://restaurantbanners.orderin.co.za/knead_652_cropped/620.jpg",
                            Name = "Knead",
                            Rank = 1,
                            Suburb = "Panorama"
                        },
                        new
                        {
                            Id = 1484,
                            City = "Cape Town",
                            LogoPath = "https://restaurantbanners.orderin.co.za/knead_652_cropped/620.jpg",
                            Name = "Knead",
                            Rank = 4,
                            Suburb = "Gardens"
                        },
                        new
                        {
                            Id = 1487,
                            City = "Cape Town",
                            LogoPath = "https://restaurantbanners.orderin.co.za/knead_652_cropped/620.jpg",
                            Name = "Knead",
                            Rank = 7,
                            Suburb = "Palmyra Junction, Claremont"
                        },
                        new
                        {
                            Id = 1488,
                            City = "Cape Town",
                            LogoPath = "https://restaurantbanners.orderin.co.za/knead_652_cropped/620.jpg",
                            Name = "Knead",
                            Rank = 8,
                            Suburb = "Golding, Kenilworth"
                        },
                        new
                        {
                            Id = 2425,
                            City = "Cape Town",
                            LogoPath = "https://restaurantbanners.orderin.co.za/knead_652_cropped/620.jpg",
                            Name = "Knead",
                            Rank = 5,
                            Suburb = "Constantia"
                        });
                });

            modelBuilder.Entity("Taco.Challenge.Restaurant.Services.DataContext.Entities.Category", b =>
                {
                    b.HasOne("Taco.Challenge.Restaurant.Services.DataContext.Entities.Restaurant", null)
                        .WithMany("Categories")
                        .HasForeignKey("RestaurantId");
                });

            modelBuilder.Entity("Taco.Challenge.Restaurant.Services.DataContext.Entities.MenuItem", b =>
                {
                    b.HasOne("Taco.Challenge.Restaurant.Services.DataContext.Entities.Category", null)
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("Taco.Challenge.Restaurant.Services.DataContext.Entities.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("Taco.Challenge.Restaurant.Services.DataContext.Entities.Restaurant", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
